### ISSUE TITLE
Fatal Error Uncaught Error: Call to undefined function DDW_Connect_Polylang_Elementor\Widgets\pll_the_languages()

### ISSUE THREAD

**Issue by sebastienserre** [deckerweb/connect-polylang-elementor#3]
Hello,

I'm Sebastien from Polylang Pro support.

One of our common customer is reporting us an issue when activating Polylang multiple Domain URL.

During the saving process, we deactivate Polylang by adding the `?deactivate-polylang=1` parameters to the URL.
It's done to be sure the domain used in the settings really exists and is reachable without Polylang.

Your plugin is testing if Polylang is activated... and it is, just several part are not loaded... and customers go through fatale:
```
[22-Apr-2020 13:11:03 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function DDW_Connect_Polylang_Elementor\Widgets\pll_the_languages() in /app/wp-content/plugins/connect-polylang-elementor/modules/widgets/polylang-language-switcher.php:273
Stack trace:
#0 /app/wp-content/plugins/elementor/includes/base/controls-stack.php(1946): DDW_Connect_Polylang_Elementor\Widgets\Polylang_Language_Switcher->_register_controls()
#1 /app/wp-content/plugins/elementor/includes/base/controls-stack.php(498): Elementor\Controls_Stack->init_controls()
#2 /app/wp-content/plugins/elementor/includes/base/widget-base.php(150): Elementor\Controls_Stack->get_stack()
#3 /app/wp-content/plugins/elementor/includes/base/controls-stack.php(291): Elementor\Widget_Base->get_stack()
#4 /app/wp-content/plugins/elementor/includes/base/controls-stack.php(2001): Elementor\Controls_Stack->get_controls()
#5 /app/wp-content/plugins/elementor/includes/base/controls-stack.php(1039): Elementor\Controls_Stack->sanitize_settings(Array)
#6 /app/wp-content/plugins/elementor/includes/base/co in /app/wp-content/plugins/connect-polylang-elementor/modules/widgets/polylang-language-switcher.php on line 273

```
We've found other users in the same kind of issue:
https://wordpress.org/support/topic/fatal-error-uncaught-error-call-to-undefined-function-pll_languages_list/

I attached a  PR: #4

**Comment by sebastienserre** [comment]
Closed by #4
